model_params:
    APC:
        ckp_path: './data/APC_epoch_160.model'
        mel_dim: 80
        hidden_size: 512
        num_layers: 3
        residual: false
        use_LLE: 1
        Knear: 10
        LLE_percent: 1
    Audio2Mouth:
        ckp_path: './checkpoints/Audio2Feature/72_Audio2Feature.pkl'
        smooth: 2
        AMP: ['XYZ', 1.5, 1.5, 1.5]  # method, x, y, z
    Headpose:
        ckp_path: './checkpoints/Audio2Headpose/61_Audio2Headpose.pkl'
        sigma: 0.3
        smooth: [3, 10]    # rot, trans
        AMP: [1, 1]    # rot, trans
        shoulder_AMP: 0.5
    Image2Image:
        ckp_path: './checkpoints/TestRender/72_Feature2Face_G.pkl'
        size: 'normal'
        save_input: 1
        

dataset_params:
    root: './data/hk_fake_38_LSP/'  # for inference
    fit_data_path: './data/hk_fake_38_LSP/3d_fit_data.npz'
    pts3d_path: './data/hk_fake_38_LSP/tracked3D_ptx.npy'  # come from 3d_fit_data['pts_3d']

VERSION: 1